stages:
  - build
  - test
  - deploy

default:
  image: openjdk:15
  before_script:
    - chmod +x gradlew
  tags:
    - docker

cache:
  key: ${CI_PROJECT_ID}
  paths:
    - .gradle

build:
  stage: build
  script:
    - ./gradlew publishToMavenLocal
  artifacts:
    paths:
      - ./build
    expire_in: 1 week

test:
  stage: test
  script:
    - ./gradlew check
   # - awk -F"," '{ instructions += $4 + $5; covered += $5 } END { print covered, "/", instructions, " instructions covered"; print 100*covered/instructions, "% covered" }' ./*/build/reports/jacoco/test/jacocoTestReport.csv
  artifacts:
    paths:
      - ./build/reports/*
    reports:
      junit:
        - ./build/test-results/test/**/TEST-*.xml

publish:
  stage: deploy
  only:
    - main
  script:
    - ./gradlew publish
  artifacts:
    paths:
      - ./build/libs/*.jar
    expire_in: 1 month

pages:
  stage: deploy
  only:
    - main
  script:
    - ./gradlew dokkaHtml
    - cp -r build/dokka/html public
  artifacts:
    paths:
      - public

dockerize-latest:
  stage: deploy
  image: docker:20
  only:
    - main
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD registry.gitlab.com
    - docker build -t registry.gitlab.com/kiliankra/pisces/flunder:latest .
    - docker push registry.gitlab.com/kiliankra/pisces/flunder:latest

dockerize-commit:
  stage: deploy
  image: docker:20
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD registry.gitlab.com
    - docker build -t registry.gitlab.com/kiliankra/pisces/flunder:${CI_COMMIT_SHORT_SHA} .
    - docker push registry.gitlab.com/kiliankra/pisces/flunder:${CI_COMMIT_SHORT_SHA}

